---
- name: Destroy all EC2 components
  hosts: localhost
  vars_files:
     - ../configuration/vars/config.yml
  tasks:
  - name: Find Instance
    ec2_instance_info:
      region: "{{ config.aws.region }}"
      filters:
        "tag:Name": "{{ config.aws.ec2.instance.name }}"
        instance-state-name: ["running"]
    register: instance_out
    ignore_errors: yes

  - name: Terminate Instance, Unregister CloudWatch Alarm, Release EIP
    block:
      - name: Unregister CloudWatch Alarm
        ec2_metric_alarm:
          state: absent
          name: "{{ config.aws.cloudwatch.name }}"
      
      # - name: Delete SNS topic # do not delete SNS topic, otherwise one would have to re-subscribe every time to get alarm emails
      #   community.aws.sns_topic:
      #     name: "{{ config.aws.cloudwatch.sns_topic.name }}"
      #     state: absent
          
      - name: Release EIP
        ec2_eip:
          state: absent
          region: "{{ config.aws.region }}"
          device_id: "{{ item.instance_id }}"
          release_on_disassociation: yes
        with_items: "{{ instance_out.instances }}"

      - name: Terminate Instance
        ec2_instance:
          state: absent
          region: "{{ config.aws.region }}"
          instance_ids: "{{ item.instance_id }}"
        when: "item.state.name != 'terminated'"
        with_items: "{{ instance_out.instances }}"
    when: instance_out is defined

  - name: Delete VPC and dependents
    block:
      - name: Get VPC Infos
        amazon.aws.ec2_vpc_net_info:
          region: "{{ config.aws.region }}"
          filters:
            "tag:Name": "{{ config.aws.ec2.vpc.name }}"
        register: vpc_out

      - name: Delete Security Group
        amazon.aws.ec2_group:
          state: absent
          region: "{{ config.aws.region }}"
          name: "{{ config.aws.ec2.vpc.group.name }}"

      - name: Find Route Table
        community.aws.ec2_vpc_route_table_info:
          region: "{{ config.aws.region }}"
          filters:
            "tag:Name": "{{ config.aws.ec2.vpc.routing_table.name }}"
        register: route_tables_out

      - name: Delete Route Table
        ec2_vpc_route_table:
          state: absent
          lookup: id
          region: "{{ config.aws.region }}"
          route_table_id: "{{ item.route_table_id }}"
          vpc_id: "{{ item.vpc_id }}"
        with_items: "{{ route_tables_out.route_tables }}"

      - name: Delete Internet Gateway
        ec2_vpc_igw:
          state: absent
          region: "{{ config.aws.region }}"
          vpc_id: "{{ item.id }}"
        with_items: "{{ vpc_out.vpcs}}"

      - name: Delete Subnet
        ec2_vpc_subnet:
          state: absent
          region: "{{ config.aws.region }}"
          cidr: "{{ config.aws.ec2.vpc.subnet.cidr }}"
          vpc_id: "{{ item.id }}"
        with_items: "{{ vpc_out.vpcs}}"

      - name: Delete VPC 
        ec2_vpc_net:
          state: absent
          region: "{{ config.aws.region }}"
          name: "{{ config.aws.ec2.vpc.name }}"
          cidr_block: "{{ config.aws.ec2.vpc.cidr }}"
